### ISSUE TITLE
Port clear-charset-maps

### ISSUE THREAD

**Issue by brotzeit** [remacs/remacs#1174]
```c
DEFUN ("clear-charset-maps", Fclear_charset_maps, Sclear_charset_maps,
       0, 0, 0,
       doc: /*
Internal use only.
Clear temporary charset mapping tables.
It should be called only from temacs invoked for dumping.  */)
  (void)
{
  if (temp_charset_work)
    {
      xfree (temp_charset_work);
      temp_charset_work = NULL;
    }

  if (CHAR_TABLE_P (Vchar_unify_table))
    Foptimize_char_table (Vchar_unify_table, Qnil);

  return Qnil;
}
```

**Comment by Bira** [comment]
I see that temp_charset_work is a static struct declared at the beginning of the file. How can that struct be accessed from Rust?

**Comment by shaleh** [comment]
If nothing else needs it, move it to Rust. Otherwise move it into a header like lisp.h.

**Comment by brotzeit** [comment]
...so bindgen handles it for you.

**Comment by Bira** [comment]
Several functions in the same file use it, so I'm going to move it to a new header included only in that file to avoid compilation warnings.
