### ISSUE TITLE
Update to latest `rand` crate

### ISSUE THREAD

**Issue by shaleh** [remacs/remacs#1242]
remacs currently uses `StdRng` because `ThreadRng` crashes for us. The latest version of the crate no longer exposes the `reseed` functionality we are using without using an implementation of the `ReseedingRng`.

Do we need it? Can we simplify this?
Does the newer `ThreadRng` work? Can we make it work?

**Comment by daichimukai** [comment]
I'm working on this now. My present aim is to check if we could reproduce seg fault using `thread_rng()` and resolve it if that happens. Although I haven't test my patch on macOS yet, I'll make WIP PR.

**Comment by shaleh** [comment]
The segfault is only on MacOS.
