### ISSUE TITLE
Move to a Remacs organisation

### ISSUE THREAD

**Issue by Wilfred** [remacs/remacs#1245]
Remacs has grown way beyond the first patches I've made :)

I'd like to make it an organisation, to reflect the community that we have around the project. Any objections / opinions?

**Comment by shaleh** [comment]
Yes please.

**Comment by harryfei** [comment]
Yeah, that's good.

**Comment by shanavas786** [comment]
Good move :+1:

**Comment by Wilfred** [comment]
Moved! :)

I've created a 'remacs' organisation, and invited all the current collaborators to be members.

Please comment if this has broken anything. I suspect Travis will need fiddling.

In general I love us giving merge power to anyone, but we should also have a few additional admins beyond me. @shaleh are you happy being an admin?

**Comment by Wilfred** [comment]
OK, Travis is running: https://travis-ci.org/remacs/remacs

The only issue I'm aware of is updating the Travis badge in the readme.

**Comment by Wilfred** [comment]
Annoyingly, I can't see the state of old Travis builds here: https://travis-ci.org/Wilfred/remacs or individual builds like https://travis-ci.org/Wilfred/remacs/builds/492195097

**Comment by Wilfred** [comment]
Based on https://help.github.com/articles/repository-permission-levels-for-an-organization/ I think 'write' permission is the right level to enable people to merge PRs. We should still be requiring an approval of PRs according to https://github.com/remacs/remacs/settings/branch_protection_rules/551755

**Comment by shaleh** [comment]
Yeah, I can admin. We can huddle on gitter and work out the people able to be staff.

**Comment by Wilfred** [comment]
Done.

I don't think there's anything left to do here, but feel free to open new issues and tag me if you see anything.
