### ISSUE TITLE
Port kill-process

### ISSUE THREAD

**Issue by brotzeit** [remacs/remacs#1260]
```c
DEFUN ("kill-process", Fkill_process, Skill_process, 0, 2, 0,
       doc: /* Kill process PROCESS.  May be process or name of one.
See function `interrupt-process' for more details on usage.  */)
  (Lisp_Object process, Lisp_Object current_group)
{
  process_send_signal (process, SIGKILL, current_group, 0);
  return process;
}
```

**Comment by jubnzv** [comment]
Not so good as first issue, because we should also port `port_send_process` [defined](https://github.com/emacs-mirror/emacs/blob/master/src/process.c#L6606) as `static`. :)

I will take it and other `process_send_process` wrappers from this file.

**Comment by jubnzv** [comment]
It's challenging task for me, I'll try it.
