### ISSUE TITLE
eval-region not available as interactive command

### ISSUE THREAD

**Issue by cjohansson** [remacs/remacs#1346]
In GNU Emacs trunk, pressing M-x, typing eval-region will evaluate current selection, however this command is not available as an interactive command in Remacs, but it is available if you run via evaluate-expression so something seems to be wrong with the auto-loading of that interactive command

![screen shot 2019-02-13 at 07 34 54](https://user-images.githubusercontent.com/924848/52691724-034a1d00-2f62-11e9-96ec-aa701d6d5ac7.png)

**Comment by brotzeit** [comment]
`intspec` is missing again.

**Comment by shaleh** [comment]
@cjohansson whenever you see this, grep for the function name as a lisp_fn in Rust source. It should have a `intspec = "something"`. If not, look at the emacs source for a DEFUN in the C. The intspec is the 3rd value after the Ffoo and Sfoo are defined. There will be 2 numbers and then a string.

**Comment by cjohansson** [comment]
Alright I'll try fixing that
