### ISSUE TITLE
remacs_sys.rs is marked as executable

### ISSUE THREAD

**Issue by agraven** [remacs/remacs#1368]
`rust_src/src/remacs_sys.rs` is marked as executable.

Is this on purpose? If so, what's the motivation behind it?

**Comment by brotzeit** [comment]
It works with the normal permissions. I can't imagine there's a reason for it,

**Comment by shaleh** [comment]
No reason. We fixed this quite a while back and a merge reversed it I think. Submit a PR.

**Comment by brotzeit** [comment]
Is there a way to include file permissions in our tests somehow ? This seems like a frequent issue.

**Comment by shaleh** [comment]
`find $path -type f -perm +111 -print` is sufficient. It only needs to be run.
