### ISSUE TITLE
Getting `Symbol's function definitions is void: key-binding` when using evil-mode

### ISSUE THREAD

**Issue by take-cheeze** [remacs/remacs#1390]
Currently built: https://github.com/remacs/remacs/commit/8a1e30df09a5ccba2f111f375b3dcd2f802133d1

Seems these relates:
https://github.com/remacs/remacs/pull/1369
https://github.com/remacs/remacs/pull/1378

**Comment by brotzeit** [comment]
Can you please test the function with vanilla remacs.

**Comment by take-cheeze** [comment]
I'm not using evil mode now so closing.
I'll try vanilla emacs next time!
