### ISSUE TITLE
Update docs to include guidance for preferring `libc::c_char` over `i8` or `u8`

### ISSUE THREAD

**Issue by shaleh** [remacs/remacs#1410]
The perennial "what is a char?" conversation.

`i8` and `u8` are both ways to say `byte` in Rust. On ARM platforms the C language `char` is `unsigned char`. This always ends up biting someone. Using `libc::c_char` ensures that remacs has the correct type regardless of the hardware implementation needs.

This is sure to be annoying because the Rust compiler and clippy will for sure suggest `i8` and not `c_char`. If we can work out a way to automatically detect this (clippy plugin??) great. For now we at least need to document it for developers.

**Comment by agraven** [comment]
I added a section in the wiki about it.
