### ISSUE TITLE
MacOS 10.14.3 Install segmentation fault in bootstrap-emacs

### ISSUE THREAD

**Issue by darkanthey** [remacs/remacs#1411]
When trying to install latest git emacs version I've got Segmentation fault.
I upgraded to 10.14 lately before Remacs compiled well on 10.13.

My PATH is:
/usr/local/opt/texinfo/bin:/Users/darkanthey/.zplug/bin:/Users/darkanthey/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

( make clean && git clean -fdx && ./autogen.sh && ./configure --enable-rust-debug --without-makeinfo && make ) > /tmp/build.log 2>&1

Build log:
https://gist.github.com/darkanthey/9ddd1747213382134c3a11ba7ee8a197

**Comment by brotzeit** [comment]
There's this message in the log:
`error: 'rustfmt' is not installed for the toolchain 'nightly-2019-03-22-x86_64-apple-darwin'`

I've seen this problem several times in the past and it's really annoying. Can you please try the toolchain from 2019-03-21. Did you change the toolchain manually ?

**Comment by brotzeit** [comment]
I forgot that this has to be fixed by reinstalling rustfmt for the new toolchain. Unfortunately this doesn't happen automatically.

**Comment by darkanthey** [comment]
Thank you for such a quick response. So I'll close this bug. I suppose this might be helpful for others.

**Comment by brotzeit** [comment]
I already documented it some time ago https://github.com/remacs/remacs/wiki/Porting-Cookbook#rustfmt

**Comment by brotzeit** [comment]
Maybe I should add a "important" or something like that...

**Comment by shaleh** [comment]
I needs to be front and center for anyone compiling remacs. Even someone wanting to try it once in a while can encounter this.
