### ISSUE TITLE
Port window-pixel-width-before-size-change

### ISSUE THREAD

**Issue by brotzeit** [remacs/remacs#1429]
```c
DEFUN ("window-pixel-width-before-size-change",
       Fwindow_pixel_width_before_size_change,
       Swindow_pixel_width_before_size_change, 0, 1, 0,
       doc: /* Return pixel width of window WINDOW before last size changes.
WINDOW must be a valid window and defaults to the selected one.

The return value is the pixel width of WINDOW at the last time
`window-size-change-functions' was run.  It's zero if WINDOW was made
after that.  */)
  (Lisp_Object window)
{
  return (make_number
	  (decode_valid_window (window)->pixel_width_before_size_change));
}
```

**Comment by Flowneee** [comment]
I'd like to try this one. I think it's reasonable to also port `window-pixel-height-before-size-change` since they are pretty close.

**Comment by brotzeit** [comment]
:+1:

**Comment by Flowneee** [comment]
@brotzeit Well, porting itself was easy :)  , but I stuck with tests for this functions, because of problem with ert: it doesn't actually change `window-pixel-width-before-size-change` during tests (probably because tests doesn't change frame and thus `window-size-change-functions` not invoked), so I unable to write tests which mutate this value inside test.

So something like this is not working (`window-pixel-width-before-size-change` always return same value):
``` elisp
(ert-deftest window-pixel-width-before-size-change ()
  (let ((original  (window-pixel-width-before-size-change (selected-window))))
    (split-window-right)
    (should-not (= original (window-pixel-width-before-size-change (selected-window))))
    )
  )
```

Any idea how to make this work?

**Comment by brotzeit** [comment]
I have similiar issues with #1212. I'm already looking for a solution.
Did you run your tests in an interactive session ?

**Comment by Flowneee** [comment]
Yes, i did. An found that it is not only problem with ert, but it also works that way with `progn` and `let`. Next code:

``` elisp
(ert-deftest window-pixel-width-before-size-change ()
  (let ((x (split-window-horizontally)) (original-pixel-width (window-pixel-width nil)))
    (print (selected-window))
    (print (window-pixel-width (selected-window)))
    (print (window-pixel-width-before-size-change (selected-window)))
    (window-resize nil 10 t)
    (print (window-pixel-width (selected-window)))
    (print (window-pixel-width-before-size-change (selected-window)))
    (should (= (window-pixel-width-before-size-change) original-pixel-width))
    )
  )
```

have exactly same output if you run it with `ert` and just `let` itself (C-x C-e). `window-pixel-width` will change, while `window-pixel-width-before-size-change` will stay in pre-split value.

**Comment by brotzeit** [comment]
Does this also work when you use another value than 10 ? I'm asking because this is the default frame size in test runs.

**Comment by Flowneee** [comment]
Yes. I tried to use different value with `window-resize`, change window size with `split-window-right`.

**Comment by brotzeit** [comment]
:+1:

**Comment by Flowneee** [comment]
Hm. Today I'm tried to find a way to manually invoke changing of `window-pixel-*-before-size-change`, but no luck . So far my ideas is:

- leave this functions without proper tests (just simple reading of values from C);
- add functionality to manually invoke resetting of `window-pixel-*-before-size`.

Second option would require quite a configuration for tests, which require both with Rust and Elisp code.

**Comment by brotzeit** [comment]
You can decide if you want to merge it without tests or give it another try. Hopefully we have a test environment that behaves exactly like an interactive session at some point.

**Comment by Flowneee** [comment]
Okay, still no luck, so I gonna leave this without tests, but I'll leave a dummy tests and a note, so we won't forget to fix this when we will have proper test environment.
