### ISSUE TITLE
Native Support for Ligatures

### ISSUE THREAD

**Issue by colonelrascals** [remacs/remacs#1443]
One of my biggest pet peeves with emacs is it lack native support for ligatures. From my understanding, this is implemented at the emacs source code. I would be great if remacs could add support. I'd be happy to help in any way possible, but would need some direction. #

**Comment by shaleh** [comment]
At the moment porting is our primary concern. Deep changes to the code make it harder for us to bring over upstream changes. We are trying to get caught up with mainline emacs.

You are 100% welcome to experiment and dig into this. I want to set your expectations on when we will accept the changes. This is definitely "not now, later please" and not "we will never consider this".

**Comment by colonelrascals** [comment]
@shaleh Totally get it! Thanks for the response! 

Look forward to watching this project grow!

ps. I'd love to donate!
