### ISSUE TITLE
Questions regarding continuous release

### ISSUE THREAD

**Issue by davidarmstronglewis** [remacs/remacs#1490]
Hey all, thanks for all your work on this!

I'm curious what the story is for remacs regarding continuous release or prebuilt binaries. Would it make sense to start doing releases as part of continuous integration or anything like that? Curious what your thoughts are on that.

**Comment by brotzeit** [comment]
If somebody is motivated to do this, why not.

**Comment by shaleh** [comment]
My only concern here is giving a false sense of stability. We are changing out deep internals and often there are not helpful tests written already.  I am not certain we are ready for users from binary. Today we seek debugging info and help from our users.

**Comment by davidarmstronglewis** [comment]
That makes a lot of sense, I guess then it makes sense to close this and revisit when Remacs is at that level of stability. Thanks, you two!

**Comment by brotzeit** [comment]
On the other hand, if people want to use a non stable remacs (and maybe report bugs ?) why not give them a chance. The version is 0.1 =)
It's also kind of too late :P
https://aur.archlinux.org/packages/remacs-git/
