### ISSUE TITLE
Port invisible-p

### ISSUE THREAD

**Issue by brotzeit** [remacs/remacs#1493]
```c
DEFUN ("invisible-p", Finvisible_p, Sinvisible_p, 1, 1, 0,
       doc: /* Non-nil if text properties at POS cause text there to be currently invisible.
POS should be a marker or a buffer position; the value of the `invisible'
property at that position in the current buffer is examined.
POS can also be the actual value of the `invisible' text or overlay
property of the text of interest, in which case the value itself is
examined.

The non-nil value returned can be t for currently invisible text that is
entirely hidden on display, or some other non-nil, non-t value if the
text is replaced by an ellipsis.

Note that whether text with `invisible' property is actually hidden on
display may depend on `buffer-invisibility-spec', which see.  */)
  (Lisp_Object pos)
{
  Lisp_Object prop
    = (NATNUMP (pos) || MARKERP (pos)
       ? Fget_char_property (pos, Qinvisible, Qnil)
       : pos);
  int invis = TEXT_PROP_MEANS_INVISIBLE (prop);
  return (invis == 0 ? Qnil
	  : invis == 1 ? Qt
	  : make_number (invis));
}
```

**Comment by ngortheone** [comment]
Hi @brotzeit , I will try to port this one. 
Since this will be my first I have a bunch of questions:

What should I do with `NATNUMP`, `MARKERP` and `TEXT_PROP_MEANS_INVISIBLE` macros?
Are there ported rust alternatives? 

I found this in `src/numbers.rs` that looks like something similar 
```rust
    pub fn is_natnum(self) -> bool {
        self.as_fixnum().map_or(false, |i| i >= 0)
    }
```

Same for `MARKERP`

src/marker.rs
```rust
    pub fn is_marker(self) -> bool {
...
```

I have not found anything that looks like `TEXT_PROP_MEANS_INVISIBLE`

**Comment by ngortheone** [comment]
What file should this go to?

**Comment by shaleh** [comment]
We tend to use the same file name as the original C. If you look for other functions ported from the same file it should be clear.

https://github.com/remacs/remacs/wiki/Porting-Cookbook is our attempt at helping new people to the code. Please point out where this is insufficient or out of date.

**Comment by brotzeit** [comment]
The cookbook is out of date, but it should still be helpful.

**Comment by ngortheone** [comment]
@brotzeit @shaleh 

I was trying to find answers in Porting Cookbook as well as other Wiki pages but here is what remains unclear to me:

1. C Macros - it is unclear which macros were already ported and how are they named.
https://github.com/remacs/remacs/wiki/Porting-Cookbook#c-macros
>The docstring should mention the original macro name.

But this clearly is not true. I have not found any docstring that would mention `NATNUMP`, `MARKERP`, `TEXT_PROP_MEANS_INVISIBLE`, but first two are clearly ported. I am still looking for the last one.

Literal question at hand:
what should I do with TEXT_PROP_MEANS_INVISIBLE?

Proposition on how to porting experience  better: we should create a table with C->Rust correspondence of all macros. Example:

C Macro | Rust counterpart | Rust file
------------ | ------------- | -------------|
NUMP |  impl LispObject, pub fn is_natnum(self) | numbers.rs
MARKERP | impl LispObject, pub fn is_marker(self) | marker.rs
XCAR| ? | ?
XCONS | ? | ?
XCDR | ?  |? 
BVAR | ? | ?
TEXT_PROP_MEANS_INVISIBLE | ? | ?

etc.
2. Documentation on `DEFSYM` is also a bit confusing.
I have added `def_lisp_sym!(Qinvisible, "invisible");` to my file but I still get 

```
error[E0425]: cannot find value `Qinvisible` in this scope
  --> src/xdisp.rs:66:39
   |
66 |         get_char_property(pos.into(), Qinvisible, Qnil)
   |                                       ^^^^^^^^^^
```

And there appears to be no way to import these `def_lisp_sym`, and `Qinvisible` is used in many files. What should I do?

**Comment by shaleh** [comment]
re: `def_lisp_sym!`

You are very close I suspect. The likely unexpected bit is you still have to import the `Qinvisible` from `remacs_sys` even though you have defined it in the Rust code.

`def_lisp_sym!` is a do nothing macro that exists solely to be detected by the `build.rs` code. When remacs is built all of the `def_lisp_sym` are found and the values generated. `remacs_sys` is how all of this generated code is accessed. If there was only Rust code this would not be quite the Rube Goldberg that it is. But these symbols are still needed in C so a proper header has to exist, which is also generated.

Here is an example looking at two related symbols: Qcase_table and Qcase_table_p
```
./rust_src/generated/globals.rs:770:pub const Qcase_table: LispObject = crate::lisp::LispObject( 242 * (std::mem::size_of::<Lisp_Symbol>() as EmacsInt));
./rust_src/generated/globals.rs:771:pub const Qcase_table_p: LispObject = crate::lisp::LispObject( 243 * (std::mem::size_of::<Lisp_Symbol>() as EmacsInt));
./rust_src/generated/bindings.rs:1118:pub const iQcase_table: u32 = 242;
./rust_src/generated/bindings.rs:1119:pub const iQcase_table_p: u32 = 243;
./src/globals.h:1542:#define iQcase_table 242
./src/globals.h:1543:DEFINE_LISP_SYMBOL (Qcase_table)
./src/globals.h:1544:#define iQcase_table_p 243
./src/globals.h:1545:DEFINE_LISP_SYMBOL (Qcase_table_p)
./src/globals.h:6012:# define Qcase_table builtin_lisp_symbol (242)
./src/globals.h:6013:# define Qcase_table_p builtin_lisp_symbol (243)
```

**Comment by shaleh** [comment]
From eval_macros.rs:
```
/// Macro that expands to nothing, but is used at build time to
/// generate the starting symbol table. Equivalent to the DEFSYM
/// macro. See also lib-src/make-docfile.c
macro_rules! def_lisp_sym {
    ($name:expr, $value:expr) => {};
}
```

**Comment by shaleh** [comment]
My personal opinion is that comments like "X is equiv of Y in the C code" limits our port. We are not going to be 1:1 in this effort. But, @ngortheone you bring up a valid point that until you learn and read a lot of code it is not clear which pieces line up. I worry that a massive lookup table will be hard to maintain. Might be worth it though 🤷‍♂

**Comment by shaleh** [comment]
You and a few others were given write privileges in the last week. This means you also have the ability to update the wiki. As you port, find places in the docs that are out of date and update them. Or at the least mark them as needing attention and then open an Issue pointing to the part that needs help. if you find yourself constantly wondering "what is this macro...." maybe a better approach is a Primer that details what the C macros do so a Rust porter can look up the macro, understand the intent, and then write the correct Rust. Documenting Emacs internals for the current generation of readers is a potentially valuable thing outside of our port too.

More documented walk throughs of porting functions would also be helpful I suspect.

**Comment by gganley** [comment]
Is there any reason this is still open after #1552 ?

**Comment by shaleh** [comment]
Nope.
