### ISSUE TITLE
Discussion: Make Codepoint a newtype?

### ISSUE THREAD

**Issue by agraven** [remacs/remacs#1501]
I propose making `multibyte::Codepoint` a `#[repr(transparent)]` newtype instead of a type alias, as it makes it easier to define methods on it. An example of a method could be a port of `char_width` from `character.c`

**Comment by nickdrozd** [comment]
I've wanted to do that for a while, but wasn't sure how. I say go for it.

**Comment by brotzeit** [comment]
You mean something like https://github.com/remacs/remacs/issues/499 ?

**Comment by agraven** [comment]
Not anything quite that sophisticated, basically just changing `pub type Codepoint = u32` to `pub struct Codepoint(u32)`.

**Comment by shaleh** [comment]
Sounds good coupled with `repr(transparent)`. https://doc.rust-lang.org/1.26.2/unstable-book/language-features/repr-transparent.html

**Comment by agraven** [comment]
I'm having a go at implementing it now. The downside to this is that `PartialEq`, `PartialOrd` has to be implemented manually for the different integer types.
