### ISSUE TITLE
Unable to connect to package repositories via HTTPS

### ISSUE THREAD

**Issue by anicholson** [remacs/remacs#1539]
This morning, I pulled to HEAD (9fe1e56a1feaa26cb33a95f69ae84282102cb5fc) and built remacs with the following:

`./configure --with-all`

and built/installed with no issues. However, when I attempted to upgrade some packages, I get this:

```
HTTP/1.1 400 Bad Request
Date: Fri, 23 Aug 2019 07:00:11 GMT
Server: Apache/2.4.38 (Debian)
Content-Length: 433
Connection: close
Content-Type: text/html; charset=iso-8859-1

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>400 Bad Request</title>
</head><body>
<h1>Bad Request</h1>
<p>Your browser sent a request that this server could not understand.<br />
Reason: You're speaking plain HTTP to an SSL-enabled server port.<br />
 Instead use the HTTPS scheme to access this URL, please.<br />
</p>
<hr>
<address>Apache/2.4.38 (Debian) Server at elpa Port 443</address>
</body></html>
```

I definitely built remacs with `gnutls` support:

`config.log`
```
configure:13222: checking for gnutls >= 2.12.2
configure:13229: $PKG_CONFIG --exists --print-errors "gnutls >= 2.12.2"
configure:13232: $? = 0
configure:13246: $PKG_CONFIG --exists --print-errors "gnutls >= 2.12.2"
configure:13249: $? = 0
configure:13287: result: yes
```

`config.status`
```
D["HAVE_GNUTLS"]=" 1"
```

and emacs believes it's available:

```
ELISP> (gnutls-available-p)
(ClientHello\ Padding Key\ Share Post\ Handshake\ Auth PSK\ Key\ Exchange\ Modes Cookie Supported\ Versions Early\ Data Pre\ Shared\ Key Session\ Ticket Record\ Size\ Limit Extended\ Master\ Secret Encrypt-then-MAC ClientHello\ Padding Server\ Certificate\ Type Client\ Certificate\ Type ALPN Heartbeat SRTP Signature\ Algorithms SRP Supported\ EC\ Point\ Formats Supported\ Groups OCSP\ Status\ Request Maximum\ Record\ Size Server\ Name\ Indication macs AEAD-ciphers ciphers digests gnutls3 gnutls)
```

this is on Arch Linux, with `gnutls` definitely installed:

```
core/gnutls 3.6.9-1 [installed]
    A library which provides a secure layer over a reliable transport layer
```

**Comment by sehnsucht13** [comment]
Hi, Remacs is based off of Emacs version 26.2. Recently, there have been some issues with TLS and connecting to the package repositories and this affects both emacs 26.2 and therefore Remacs as well. I have not ran into this issue but I took a quick peek at the emacs subreddit. Apparently, the following is a workaround which can be put into your init.el.

`(setq gnutls-algorithm-priority "NORMAL:-VERS-TLS1.3")`

Please give that a shot and let us know if it resolves your problem.

**Comment by anicholson** [comment]
@sehnsucht13 thanks for the heads-up; this resolved the issue for me :)

<3
