### ISSUE TITLE
lsp: wrong-number-of-arguments json-serialize 5

### ISSUE THREAD

**Issue by guskovd** [remacs/remacs#1562]
On first call on my .cpp buffer (lsp)
I get an error:

File mode specification error: (wrong-number-of-arguments json-serialize 5)

--
There is no such error in emacs

**Comment by yyoncho** [comment]
AFAIK json.c changes are not ported. To fix that you could force lsp-mode to use json.el for JSON handling. FTR it will be interesting to compare the performance of serde JSON parsing with gnu emacs jansson implementation.

**Comment by guskovd** [comment]
Not playable in new version of lsp.el
