### ISSUE TITLE
Mission criticality of remacs?

### ISSUE THREAD

**Issue by Kreyren** [remacs/remacs#1587]
The one thing i hate on emacs is that it is not very suitable for mission critical environment for following reasons:
- Insufficient detection of memory leaks
- Long startup
- Likely to hang as elisp's functions like `read-string` does not have a timeout for the user to input a text and timeout for how much time the end-user has to finish the sequence. 
- other issues

Thus proposing to update ![Design Goals](https://github.com/remacs/remacs#design-goals) to adapt the development for mission critical environment alike:
1. Usage in aviation hardware
2. Usage in kubernetes i.e simmilar to gitpod.io

**Comment by Kreyren** [comment]
Based on https://github.com/remacs/remacs/issues/305 it seems that remacs wants to achieve  a feature parity with GNU Emacs while rewriting the C core in rust so this doesn't seem actionable here -> Maybe implement these in GNU Emacs so that it would be implemented here?

**Comment by nickdrozd** [comment]
Remacs is experimental hobby software, and therefore it should absolutely not be used for anything mission critical under any circumstances.
